### ISSUE TITLE
[ssd-resnet34] SERVER: Performance Result is INVALID

### ISSUE THREAD

**Issue by byounghak36** [ltechkorea/inference_results_v1.0#16]
# ssd-resnet34

> `Offline` and `Server`
> Accuracy: 99(`default`)

- **`Server` Result is INVALID**

## `Offline`

- [x] `default`

## `Server`

- [x] `default`: `INVALID`

## Command

```bash
docker run --gpus=all --rm -t -w /work \
        -v /home/jay/work/inference-v1.0/closed/LTechKorea:/work -v /home/jay:/mnt//home/jay \
        --cap-add SYS_ADMIN --cap-add SYS_TIME \
        -e NVIDIA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 \
        --shm-size=32gb \
        -v /etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:ro \
        --security-opt apparmor=unconfined --security-opt seccomp=unconfined \
        --name mlperf-inference-jay -h mlperf-inference-jay --add-host mlperf-inference-jay:127.0.0.1 \
        --user 1001:1001 --net host --device /dev/fuse \
        -v /opt/data/scratch.mlperf_inference:/opt/data/scratch.mlperf_inference -v /opt/data/Dataset:/opt/data/Dataset  \
        -e MLPERF_SCRATCH_PATH=/opt/data/scratch.mlperf_inference \
        -e HOST_HOSTNAME=ltech-gpu10 \
        -e LD_LIBRARY_PATH=:/usr/local/cuda/lib64:/usr/lib/x86_64-linux-gnu:/home/jay/work/inference-v1.0/closed/LTechKorea/build/inference/loadgen/build:/usr/local/cuda-11.1/targets/x86_64-linux/lib/ \
         \
        mlperf-inference:jay make run_harness RUN_ARGS="--benchmarks=ssd-resnet34 --scenarios=Offline,Server --config_ver=default --test_mode=SubmissionRun --verbose --fast"
```

## Results

```
======================= Perf harness results: =======================

V100S-PCIE-32GBx8_TRT-default-Offline:
    ssd-resnet34: result_samples_per_second: 943.488, Result is VALID

V100S-PCIE-32GBx8_TRT-default-Server:
    ssd-resnet34: result_scheduled_samples_per_sec: 6174.3, Result is INVALID


======================= Accuracy results: =======================

V100S-PCIE-32GBx8_TRT-default-Offline:
    ssd-resnet34: Accuracy = 20.111, Threshold = 19.800. Accuracy test PASSED.

V100S-PCIE-32GBx8_TRT-default-Server:
    ssd-resnet34: Accuracy = 20.111, Threshold = 19.800. Accuracy test PASSED.

make launch_docker   0.45s user 12.55s system 0% cpu 22:38.32 total
```
